// Importar este módulo registra todos los efectos disponibles. En tandas futuras se añaden más imports.
import './gain';
import './echo';
import './stereo-echo';
import './reflector';
import './reverb';
import './tremolo';
import './autopanner';
import './chorus';
import './rotary';
import './fractal-doubler';
import './limiter';
import './dynamics';
import './deesser';
import './tubewarmth';
import './sigmoid';
import './equalizer';
import './equalizer-bw';
import './pitch';
